### PR TITLE
Remove react and update eslint + jest configs

### LINKED ISSUE #1: Remove react from package.json
Currently, react is part of package.json, we should remove this. Removing actually throwing the document not defined issue when running test cases, have to fix this.

### PR DESCRIPTION
**Pull request by amogower**
**What**: Resolve #1 

**Why**:  Removal of React from package.json

**How**: Removed react from devDependencies and updated eslint + jest configs to handle document not defined issue when running test cases

**Checklist**:

* [ ] Documentation N/A
* [x] Tests
* [x] Ready to be merged
* [x] Added myself to contributors table

### CODE REVIEW

**Comment by antsmartian** [comment]
Thanks! Looks like build is failing in node 6.

**Comment by amogower** [comment]
Yeah sorry, I meant to fix this the other day but work was manic. I'll sort it out this weekend.

**Comment by antsmartian** [comment]
Don't worry, take your time. I will also try to see what happened here.

**Comment by amogower** [comment]
It's something to do with the newer version of dom-testing-library using Object.entries

**Comment by antsmartian** [comment]
Yes, I guess `dom-testing-library` works only on `node 7`. 🤔 If that's the case, its good, I can go ahead and merge this.

**Comment by amogower** [comment]
Either that, or could look into wrapping the library with any necessary polyfills?  Up to you, I don't use anything below Node 8 these days anyway so doesn't affect me.

**Comment by antsmartian** [comment]
Yes, I'm thinking the same. Hardly people use node 6. Alright, I have a look at by evening and merge it. Thank you so much for your time in this!

**Comment by antsmartian** [comment]
@amogower Sorry, there is a conflict now (merged a PR now). Could you resolve it please?

**Comment by amogower** [comment]
Sure, just sorting now

**Comment by amogower** [comment]
Anything else you need from me in regards to this @antsmartian?

**Comment by antsmartian** [comment]
@amogower Nothing, it's good to go. But I couldn't able to run `npm run build` on this PR, which throws syntax error. On master it works. The error is thrown on this line:

```
SyntaxError: src/index.js: Unexpected token (29:4)
  27 |       // folks can use all the same utilities we return in the first place that are bound to the container
  28 |     },
> 29 |     ...getQueriesForElement(baseElement),
     |     ^
  30 |   }
  31 | }
  32 | 
```

I'm just looking here, what went wrong.

**Comment by amogower** [comment]
@antsmartian, I know what this is, will sort it

**Comment by amogower** [comment]
@antsmartian should be OK now but let me know if not

**Comment by antsmartian** [comment]
@amogower : Thanks a ton `0.3.0` is published: https://www.npmjs.com/package/preact-testing-library.

**Pull request merged**
